# Generated by Django 4.0.2 on 2022-03-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0003_alter_kunde_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verkmerk',
            fields=[
                ('gespraechs_id', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, verbose_name='GesprächsNr')),
                ('datum_des_Gespraechs', models.DateTimeField(auto_now=True)),
                ('gesclecht', models.CharField(blank=True, choices=[('Frau', 'Frau'), ('Herrn', 'Herrn')], default='', max_length=50, null=True, verbose_name='Anrede')),
                ('mitarbeiter', models.CharField(default='', max_length=400, verbose_name='Mitarbeiter Name')),
                ('betreff', models.CharField(default='', max_length=100, null=True)),
                ('inhalt_des_gespraechs', models.CharField(blank=True, choices=[('Ruft wieder an', 'Ruft wieder an'), ('Wünscht Rückruf', 'Wünscht Rückruf'), ('Wünscht Termin', 'Wunscht Termin')], default='', max_length=50, null=True)),
                ('comments', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
            ],
        ),
    ]
