# Generated by Django 4.0.2 on 2022-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunden', '0004_verkmerk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunde',
            name='letzte_Gespraeche',
        ),
        migrations.RemoveField(
            model_name='verkmerk',
            name='inhalt_des_gespraechs',
        ),
        migrations.AddField(
            model_name='verkmerk',
            name='inhalt_des_gesprächs',
            field=models.CharField(blank=True, choices=[('Ruft wieder an', 'Ruft wieder an'), ('Wünscht Rückruf', 'Wünscht Rückruf'), ('Wünscht Termin', 'Wunscht Termin'), ('Anderes Thema', 'Anderes Thema')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verkmerk',
            name='gespraechs_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='GesprächsNr'),
        ),
    ]
